# Generated by Django 2.0.13 on 2019-04-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('monthly_max_requests', models.PositiveIntegerField(default=1000, verbose_name='Monthly max requests')),
                ('daily_max_requests', models.PositiveIntegerField(default=100, verbose_name='Daily max requests')),
                ('status', models.CharField(choices=[('A', 'Disabled'), ('B', 'Monthly quota'), ('C', 'Daily quota'), ('D', 'Unlimited')], default='A', max_length=1, verbose_name='Key Status')),
            ],
        ),
        migrations.CreateModel(
            name='UserKeyUsage',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('requests', models.PositiveIntegerField(default=0, verbose_name='Requests')),
                ('userkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserKey')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
