# Generated by Django 2.0.13 on 2019-04-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('localized_name', models.CharField(max_length=50, verbose_name='Localized name')),
                ('nicknames', models.TextField(blank=True, verbose_name='Nicknames')),
                ('use_custom_image', models.BooleanField(default=False, verbose_name='Use custom image?')),
                ('custom_image', models.ImageField(blank=True, upload_to='custom_images', verbose_name='Custom image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
