# Generated by Django 2.0.13 on 2019-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Item cost'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_recipe',
            field=models.BooleanField(default=False, verbose_name='Is item recipe?'),
        ),
    ]
